In [1]:
import numpy as np

In [2]:
a = np.array([[3,1],
             [2,4]])

In [3]:
ev = np.linalg.eig(a)

In [4]:
print(ev[0])

[2. 5.]


In [5]:
print()

In [6]:
print(ev[1])

[[-0.70710678 -0.4472136 ]
 [ 0.70710678 -0.89442719]]


In [7]:
b = np.array([[-2,4],
             [-1,3]])

In [8]:
b

array([[-2,  4],
       [-1,  3]])

In [9]:
ev = np.linalg.eig(b)

In [10]:
print(ev[0])

[-1.  2.]


In [11]:
print(ev[1])

[[-0.9701425  -0.70710678]
 [-0.24253563 -0.70710678]]


In [12]:
a = np.array([[2,1],[4,3]])

In [13]:
eva = np.linalg.eig(a)

In [16]:
print(eva[0])

[0.43844719 4.56155281]


In [15]:
eva[0]

array([0.43844719, 4.56155281])

In [17]:
b = np.array([[3,2,1],
             [2,2,2],
             [1,2,3]])

In [18]:
evb = np.linalg.eig(b)

In [20]:
print(evb[0])

[ 6.00000000e+00  2.00000000e+00 -1.26101453e-16]


In [21]:
print(evb[1])

[[-5.77350269e-01 -7.07106781e-01  4.08248290e-01]
 [-5.77350269e-01 -1.76777545e-16 -8.16496581e-01]
 [-5.77350269e-01  7.07106781e-01  4.08248290e-01]]


In [22]:
c = np.eye(3)

In [23]:
print(c)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [24]:
evc = np.linalg.eig(c)

In [25]:
evc[0]

array([1., 1., 1.])

In [26]:
evc[1]

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [27]:
a = np.array([[4,2],[2,1]])

In [28]:
np.linalg.eigh(a)

(array([0., 5.]), array([[ 0.4472136 , -0.89442719],
        [-0.89442719, -0.4472136 ]]))

In [ ]:
pd.